### ISSUE TITLE
مشکلات

### ISSUE THREAD

**Issue by DevxRF** [Azumi67/Reverse_tls#1]
فعال بودن iptable باعث از کار افتادن تونل میشه
فعال بودن speedtest بعد از تست تو سایت تانل از کار میوفته

**Comment by Azumi67** [comment]
لطفا بررسی کنید که پورتی باعث اختلال در تانل و Iptable شما نشده باشه. همیشه status service مورد نظر رو بخونید و ببینید چه خطایی داده. 
برای اسپید تست هم من تست کردم و مشکلی نبوده. سرور فیلتر شده هم هست. 

![1704193324734](https://github.com/Azumi67/Reverse_tls/assets/119934376/eccdefd5-609d-4353-87ba-1f83d3157c6e)
