### ISSUE TITLE
reversse udp and tcp together

### ISSUE THREAD

**Issue by dreamboxone** [Azumi67/Reverse_tls#10]
Is it possible to use both TCP and UDP protocols from Iran to overseas server via reverse TLS tunnel?
TCP  and UDP separately are ok but it is not possible to work simultanesously
please kindly help

**Comment by Azumi67** [comment]
Hello there. To use both tcp and udp protocols simultaneously, I think you could do that with rathole.
Please check that project and by checking I mean the original dev's page.

**Comment by mhosseint** [comment]
سلام منم این مشکلو دارم
