### ISSUE TITLE
مصرف دیتا سرور ایران

### ISSUE THREAD

**Issue by hayousef68** [Azumi67/Reverse_tls#11]
سلام آزومی عزیز خسته نباشی .ممنون بابت اسکریپت های عالی که نوشتی
یه سوالی ک داشتم من از این روش استفاده میکنم آیا مصرف دیتا روی سرور ایران بیشتر میکنه یا مثل آی پی فوروارد هر چقدر مصرف کنی اون محاسبه میشه

**Comment by Azumi67** [comment]
سلام مرسی. به هر حال ریورس کمی مصرف رو بالاتر می‌بره . به نظرم در موردش به صورت کامل داخل گوگل مطالعه کنید چون فاکتور های زیادی داره .

**Comment by hayousef68** [comment]
تا چه حدودی مصرف رو بالا میبره استاد
داخل گوگل چیز به درد بخوری پیدا نکردم .خود شما جواب بدین عالی میشه.ممنون

**Comment by Azumi67** [comment]
خواستم به اطلاع شما برسانم یک نفر که تست های دقیق تری انجام داده بررسی کرده که مصرف این تانل با دایرکت برابر است اما خب طبق مقاله هایی  که من خوندم این مورد به فاکتورهای زیادی ربط داره. به هر حال خوبه که در این زمینه تستی انجام شده است .
