### ISSUE TITLE
سرور ایران

### ISSUE THREAD

**Issue by KanekiDevPro** [Azumi67/Reverse_tls#2]
سلام وقت بخیر ما میایم تانل رو نصب کنیم تو سرور ایران این ارور رو میده 

go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go:8:8: //go:build comment without // +build comment

باید چیکار کنیم

**Comment by Azumi67** [comment]
سلام ببینید این مشکل شما رو حل میکنه 

nano go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go

باید اینطوری باشه 

//go:build (linux || aix || zos) && !appengine && !tinygo
// +build linux aix zos
// +build !appengine
// +build !tinygo

package isatty

import "golang.org/x/sys/unix"

و ادامه کد
