### ISSUE TITLE
ارور

### ISSUE THREAD

**Issue by KanekiDevPro** [Azumi67/Reverse_tls#3]
سلام این چه اروریه نمیزاره اسکریپت بالا بیاد

go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go:8:8: //go:build comment without // +build comment

**Comment by Azumi67** [comment]
سلام ببینید این مشکل شما رو حل میکنه

nano go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go

باید اینطوری باشه

//go:build (linux || aix || zos) && !appengine && !tinygo
// +build linux aix zos
// +build !appengine
// +build !tinygo

package isatty

import "golang.org/x/sys/unix"

و ادامه کد
