### ISSUE TITLE
قطعی سرور ایران

### ISSUE THREAD

**Issue by benymintm** [Azumi67/Reverse_tls#4]
سلام وقت بخیر اول ممنونم بابت این اسکیریپ خفن که به صورت رایگان در اختیار ما گذاشتین در این روز های سخت سوال بنده اینه سرور ایران من قطع میشه یهو و مجبورم داخل سرور ایران اسکیریپ مجدد ران کنم و ریستارت کنم تانل رو تا دوباره کار بده ممنون میشم کمکم کنید

**Comment by Azumi67** [comment]
سلام خواهش میکنم. ببینید لاگ های تانل و سرویس رو بررسی کنید. بعد حتما سرور ایرانتون رو مانیتور کنید و ببینید که قطعی یا تایم اوت نداشته باشه. این روز ها خیلی از سرور ها مشکلات دارند . من برای همه تانل ها ریست تایمر قرار دادم و میتونید حتی اتوماتیک ویرایش هم کنید چون اضافه شده. با بررسی اینها میتونید مشکل را بیابید.
