### ISSUE TITLE
عدم اجرای اسکریپت

### ISSUE THREAD

**Issue by mehdivaezi** [Azumi67/Reverse_tls#5]
فکر کنم با تغییر دیروز اسکریپت ران نمیشه

go run tls.go
go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go:8:8: found packages unix (affinity_linux.go) and main (mkasm.go) in /root/go/pkg/mod/golang.org/x/sys@v0.14.0/unix

دمت گرم بابت این اسکرپیت فوق العاده خفن ات.

**Comment by Azumi67** [comment]
سلام. مرسی . ببینید با این دستور مشکل شما حل میشه . چون به نظر میاد اخرین ورژن sys رو ندارید. 
go get -u golang.org/x/sys

**Comment by mehdivaezi** [comment]
درود بهتون
متاسفانه حل نشد

```tls.go                               100%[===================================================================>]  83.80K  --.-KB/s    in 0.05s   

2024-01-21 19:41:22 (1.66 MB/s) - ‘tls.go’ saved [85809/85809]

go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go:8:8: found packages unix (affinity_linux.go) and main (mkasm.go) in /root/go/pkg/mod/golang.org/x/sys@v0.16.0/unix```

بعد از اینجا ، کامل خارج میشه.

**Comment by mehdivaezi** [comment]
درود بهتون
متاسفانه حل نشد

`tls.go                               100%[===================================================================>]  83.80K  --.-KB/s    in 0.05s   

2024-01-21 19:41:22 (1.66 MB/s) - ‘tls.go’ saved [85809/85809]

go/pkg/mod/github.com/mattn/go-isatty@v0.0.20/isatty_tcgets.go:8:8: found packages unix (affinity_linux.go) and main (mkasm.go) in /root/go/pkg/mod/golang.org/x/sys@v0.16.0/unix`

بعد از اینجا ، کامل خارج میشه.

**Comment by mehdivaezi** [comment]
مشکل از نسخه golang بود. 
به نسخه ۱.۲۱ ارتقاء دادم حل شد.
