### ISSUE TITLE
گزارش مشکل در استفاده طولانی مدت

### ISSUE THREAD

**Issue by mhosseint** [Azumi67/Reverse_tls#6]
سلام وقت بخیر
واقعا ممنون بابت این پروژه بسیار کارآمد و حرفه ای....
فقط یه مشکلی برای بنده وجود دارد اونم اینکه وقتی تونل رو انجام میدیم مثلا برای یکی دو ساعت خیلی سرعت و پینگ عالیه ولی بعدش قاطی میکنه و پینگ و... کلا قطع میشه و مجبورم بیام داخل سرور و یکبار ریستارت کنم.
زمانی که ریستارت میکنم یا تونل رو یکبار استاپ و دوباره متصل میکنم درست میشه ولی بازم بعد چند ساعت دوباره همین اتفاق براش می افته
آیا راه حلی برای این موضوع وجود داره؟ کاری میتونیم بکنیم که مثلا هر ۱۰ دقیقه یکبار خودش ریستارت بکنه؟
ممنون میشم راهنمایی بفرمایید.
باتشکر

**Comment by Azumi67** [comment]
سلام مرسی. بله برای این مورد هم به زودی یک دستور به ریست تایم اضافه میکنم که فکر کنم باعث بشه این مشکل برطرف با کمتر به چشم بیاد. چون منابع بسیار بالایی استفاده میکنه. حتما optimizer هم استفاده کنید .

**Comment by mhosseint** [comment]
سلام مجدد
دقیقا کدام optimizer را باید استفاده کنم و چه گزینه ای را انتخاب کنم؟
چون من وقتی optimizer نصب کردم وضعیتش بدتر و ناپایدار تر شد.

**Comment by Azumi67** [comment]
سلام. اوپتیمایزر اقای هاشمی رو استفاده کردید یا اپیران ؟

**Comment by mhosseint** [comment]
سلام هر دوتا رو تست کردم ولی هیچ فرقی ندارند. شما بفرمایید کدوم بهتر هست و چیکار کنم بنده هم همون کار رو انجام بدم.

**Comment by talebian1375** [comment]
سلام

متشکرم بابت زحماتت
مشکل اینجاست که بعد یک یا دو ساعت(بسته به ترافیک یا رم سرور)حجم زیادی از رم رو اشغال میکنه.
با تغییر دادن زمان ری استارت در cron مشکل حل شد
مثلا هر 10 دقیقه

> */10 * * * * /etc/tls.sh

البته تو سرور خارج هم همین اتفاق میفته که با همین روش حل میشه.

**Comment by mhosseint** [comment]
سلام ارادت
ممنون از پاسختون ولی من متوجه منظور شما نشدم؟ یعنی دقیقا چه کاری انجام بدیم؟
همین دستوری که فرستادید رو داخل سرور وارد کنیم کفایت میکنه؟ یا باید مراحل خاصی رو انجام بدیم؟
ممنون میشم راهنمایی بفرمایید

**Comment by Azumi67** [comment]
> سلام
> 
> متشکرم بابت زحماتت مشکل اینجاست که بعد یک یا دو ساعت(بسته به ترافیک یا رم سرور)حجم زیادی از رم رو اشغال میکنه. با تغییر دادن زمان ری استارت در cron مشکل حل شد مثلا هر 10 دقیقه
> 
> > */10 * * * * /etc/tls.sh
> 
> البته تو سرور خارج هم همین اتفاق میفته که با همین روش حل میشه.

سلام. بسیار عالی . به زودی به دستور ریست kill اجباری هم اضافه میکنم.

**Comment by talebian1375** [comment]
ابتدا وارد cron بشید

>  crontab -e

به جای دستور پیشفرض
این دستور جایگذاری بشه

> */10 * * * * /etc/tls.sh

بعد ctrl+x 
بعد y و اینتر
سپس به ترتیب 

> systemctl daemon-reload

> systemctl restart cron

**Comment by talebian1375** [comment]
> > سلام
> > متشکرم بابت زحماتت مشکل اینجاست که بعد یک یا دو ساعت(بسته به ترافیک یا رم سرور)حجم زیادی از رم رو اشغال میکنه. با تغییر دادن زمان ری استارت در cron مشکل حل شد مثلا هر 10 دقیقه
> > > */10 * * * * /etc/tls.sh
> > 
> > 
> > البته تو سرور خارج هم همین اتفاق میفته که با همین روش حل میشه.
> 
> سلام. بسیار عالی . به زودی به دستور ریست kill اجباری هم اضافه میکنم.

ممنونم ازت .خیلی موثر هست زحماتت.

**Comment by Azumi67** [comment]
> سلام ارادت ممنون از پاسختون ولی من متوجه منظور شما نشدم؟ یعنی دقیقا چه کاری انجام بدیم؟ همین دستوری که فرستادید رو داخل سرور وارد کنیم کفایت میکنه؟ یا باید مراحل خاصی رو انجام بدیم؟ ممنون میشم راهنمایی بفرمایید

دستور Kill اضافه شد. تایمتون رو هم از ساعت پیش فرض یا به صورت دستی یا از طریق منو به دقیقه تغییر بدید و ببینید چطور شده است. بهم اطلاع بدید مرسی.

**Comment by mhosseint** [comment]
سلام، خیلی ممنون
بنده دستور نصب اسکریپت را داخل سرور وارد کردم تا اجرا بشه بعد از طریق خود منو ریست تایم رو گذاشتم رو ۵ دقیقه و بعد یکبار ریستارت کردم.
اما حقیقتا تفاوت ملموسی مشاهده نکردم و فرقی نکرد.
کار خاص دیگری میبایست انجام بدم؟

**Comment by Azumi67** [comment]
> سلام، خیلی ممنون بنده دستور نصب اسکریپت را داخل سرور وارد کردم تا اجرا بشه بعد از طریق خود منو ریست تایم رو گذاشتم رو ۵ دقیقه و بعد یکبار ریستارت کردم. اما حقیقتا تفاوت ملموسی مشاهده نکردم و فرقی نکرد. کار خاص دیگری میبایست انجام بدم؟

باید دوباره کانفیگ کنید.

**Comment by mhosseint** [comment]
یعنی سرور رو حذف کنم از اول؟
یا اینکه فقط stop بزنم و از اول تونل بزنم؟

**Comment by Azumi67** [comment]
> یعنی سرور رو حذف کنم از اول؟ یا اینکه فقط stop بزنم و از اول تونل بزنم؟

نه فقط پاکش میکنید و دوباره کانفیگ میکنید .

**Comment by mhosseint** [comment]
انجام دادم و روی ۱۰ دقیقه هم تنظیم کردم. ولی ظاهرا تغییر مثبتی نکرد. یکی از سرور هام یکم پایدار تر شد ولی پینگش رفت بالا و یکی دیگه از سرورم کلا قطع شد و یا پینگ خیلی خیلی بالایی میگیره که عملا کار نمیکنه و کرش هم میکنه

**Comment by Azumi67** [comment]
> انجام دادم و روی ۱۰ دقیقه هم تنظیم کردم. ولی ظاهرا تغییر مثبتی نکرد. یکی از سرور هام یکم پایدار تر شد ولی پینگش رفت بالا و یکی دیگه از سرورم کلا قطع شد و یا پینگ خیلی خیلی بالایی میگیره که عملا کار نمیکنه و کرش هم میکنه

روی پینگ اینها کاری نمیکنه . بررسی کنید ببینید چطوریه . دستور kill هم اضافه کردم . ببینید چطوریه اگر خوب نبود یه همون قبلی بر میگردونم . میتونم دستور drop caches هم اضافه کنم اما اون مشکلات خاص خودش رو داره . به من اطلاع بدید که دستور kill برای شما چطور عمل می‌کنه . اگر بهتر بود که میذاریم بمونه وگرنه حذفش میکنم .

**Comment by mhosseint** [comment]
سلام. دستور kill نمیدونم چی هست ولی روی یکی از سرور هام فعلا خیلی خوب کار میکنه و احساس میکنم کمی پایدارتر شده البته باید بزاریم یه چند ساعتی بگذه تا مشخص بشه و فعلا خوبه
اما روی اون یکی سرورم کلا منابع رو درگیر کرد و سرور کرش کرد در این حد که حتی با ssh نمیتونم وارد سرور بشم.

**Comment by Azumi67** [comment]
> سلام. دستور kill نمیدونم چی هست ولی روی یکی از سرور هام فعلا خیلی خوب کار میکنه و احساس میکنم کمی پایدارتر شده البته باید بزاریم یه چند ساعتی بگذه تا مشخص بشه و فعلا خوبه اما روی اون یکی سرورم کلا منابع رو درگیر کرد و سرور کرش کرد در این حد که حتی با ssh نمیتونم وارد سرور بشم.

خیلی منابع بالایی استفاده می‌کنه و باید یوزر هاتون رو مدیریت کنید وگرنه کرش می‌کنه. اون سرور رو هارد ریبوت کنید   Optimizer کمی بهش کمک می‌کنه .

**Comment by mhosseint** [comment]
کدام Optimizer رو نصب کنم؟

**Comment by Azumi67** [comment]
> کدام Optimizer رو نصب کنم؟

میتونید برای اقای هاشمی رو تست کنید.

**Comment by mhosseint** [comment]
کدام گزینه رو در هنگام نصب اسکریپت آقای هاشمی باید انتخاب کنم؟ مراحل نصب رو میگید لطفا؟

**Comment by Azumi67** [comment]
> کدام گزینه رو در هنگام نصب اسکریپت آقای هاشمی باید انتخاب کنم؟ مراحل نصب رو میگید لطفا؟

گزینه یک

**Comment by DevxRF** [comment]
سلام این مشکل با optimizer مطمئنا حل نمیشه من چند روزی هست تست میکنم این مشکل از سمت اسکریپت شما در کرون اتفاق میوفته متاسفانه من حتی با چیسل هم تست کردم با منابع سخت افزاری و پورت ها متفاوت و متوجه شدم کرون به درستی عمل نمیکنه و ریستارت انجام نمیشه که فکر میکنم برای سرورها با اتصال بالای 50 تا این اتفاق بیشتر رخ میده تو بازه ی کوتاه تر بخصوص اگر یک اینباند از تعداد یوزر بالایی برخوردار باشه که دیگه اصلا افتضاح میشه برای کانفیگ های ریالیتی هم که تعداد درخواست رو یک پورت زیاده حتی رو تعداد پایین دچار مشکل میشه وقتی ریسارت دستی انجام میشه مشکل برطرف میشه و دوباره باز بسته به تعداد اتصالات و درخواست ها این مشکل بر میگرده من هم چندین روز از این اسکریپت و هم دوروزی از چیسل استفاده کردم که همین مشکل رو هر دو اسکریپت هست حتی یکی دیگه از دوستان این مورد رو توی چیسل هم گزارش کردن

**Comment by Azumi67** [comment]
> سلام این مشکل با optimizer مطمئنا حل نمیشه من چند روزی هست تست میکنم این مشکل از سمت اسکریپت شما در کرون اتفاق میوفته متاسفانه من حتی با چیسل هم تست کردم با منابع سخت افزاری و پورت ها متفاوت و متوجه شدم کرون به درستی عمل نمیکنه و ریستارت انجام نمیشه که فکر میکنم برای سرورها با اتصال بالای 50 تا این اتفاق بیشتر رخ میده تو بازه ی کوتاه تر بخصوص اگر یک اینباند از تعداد یوزر بالایی برخوردار باشه که دیگه اصلا افتضاح میشه برای کانفیگ های ریالیتی هم که تعداد درخواست رو یک پورت زیاده حتی رو تعداد پایین دچار مشکل میشه وقتی ریسارت دستی انجام میشه مشکل برطرف میشه و دوباره باز بسته به تعداد اتصالات و درخواست ها این مشکل بر میگرده من هم چندین روز از این اسکریپت و هم دوروزی از چیسل استفاده کردم که همین مشکل رو هر دو اسکریپت هست حتی یکی دیگه از دوستان این مورد رو توی چیسل هم گزارش کردن

سلام شما لطفا با دستور tail و journalctl بررسی‌کنید که 
سرویس کرون اجرا شده یا خیر و لطفا لاگ ها رو بفرستید .
چون دستور کرون چیزی نداره که بخواد به طور مثال اشتباه انجام بشه .پس لاگ ها را بررسی کنید و interval ریست تایم رو نگاه کنید .

**Comment by DevxRF** [comment]
> > سلام این مشکل با optimizer مطمئنا حل نمیشه من چند روزی هست تست میکنم این مشکل از سمت اسکریپت شما در کرون اتفاق میوفته متاسفانه من حتی با چیسل هم تست کردم با منابع سخت افزاری و پورت ها متفاوت و متوجه شدم کرون به درستی عمل نمیکنه و ریستارت انجام نمیشه که فکر میکنم برای سرورها با اتصال بالای 50 تا این اتفاق بیشتر رخ میده تو بازه ی کوتاه تر بخصوص اگر یک اینباند از تعداد یوزر بالایی برخوردار باشه که دیگه اصلا افتضاح میشه برای کانفیگ های ریالیتی هم که تعداد درخواست رو یک پورت زیاده حتی رو تعداد پایین دچار مشکل میشه وقتی ریسارت دستی انجام میشه مشکل برطرف میشه و دوباره باز بسته به تعداد اتصالات و درخواست ها این مشکل بر میگرده من هم چندین روز از این اسکریپت و هم دوروزی از چیسل استفاده کردم که همین مشکل رو هر دو اسکریپت هست حتی یکی دیگه از دوستان این مورد رو توی چیسل هم گزارش کردن
> 
> سلام شما لطفا با دستور tail و journalctl بررسی‌کنید که سرویس کرون اجرا شده یا خیر و لطفا لاگ ها رو بفرستید . چون دستور کرون چیزی نداره که بخواد به طور مثال اشتباه انجام بشه .پس لاگ ها را بررسی کنید و interval ریست تایم رو نگاه کنید .

مهندس رو چیسل بودم تازه مجدد ریورس نصب کردم و رو دقیقه گذاشتم تایم ریست رو نتیجه رو اعلام میکنم خدمتتون
ولی مطمئنا تو ساعتی هر دو اسکریپت تو تعداد یوزر بالا این اتفاق که پینگ میره بالا یا اصلا اتصال برقرار نمیشه بخصوص رو اینباندی که تعداد یوزر بیشتری داره و همون طور که گفتم از این اسکریپت من خیلی وقته استفاده میکنم و تعداد یوزرهای انلاینم که از 40 فراتر رفت این اتفاق رخ داده حالا دوستان میتونن باز هم با اعلام تعداد یوزر و نوع کانفیگ شما رو به چیزی که میخواهید برسونن برای رفع مشکل من خودم از vmess و vless reality کانفیگ میدم البته که بیشتر vmess هستن

**Comment by DevxRF** [comment]
اینم در ادامه بگم بررسی کردم دیدم تو این بازه افرادی هم که متصل هستند سرعتش فوق العاده میاد پایین و تو پنل که چک میکنیم اصلا نمیتونن از پورت استفاده کنن در صورتی که اصلا مشکلی رو سرور نیست هم خارج هم سرور دیگرو تست کردم و مشکلی رو سرعت خود سرورها نیست


حتی پینگ بین دو سرور خیلی عالیه
سرعت دانلود و آپلود داخل سرورها عالیه
ولی تو پنل x-ui که نگاه میکنم
با 50 تا آنلاین نهایت 1 مگ از پورت در حال استفادست
ولی بعد از ریسارت دستی مشکل حل میشد و کاربرا سرعتشون برمیگشت رو حالت عادی و مجدد سرعت دانلود و آپلودی که تو پنل نمایش داده میشد برمیگشت رو حالت قبل که بین 12 تا 15 هست برای من

**Comment by Azumi67** [comment]
> اینم در ادامه بگم بررسی کردم دیدم تو این بازه افرادی هم که متصل هستند سرعتش فوق العاده میاد پایین و تو پنل که چک میکنیم اصلا نمیتونن از پورت استفاده کنن در صورتی که اصلا مشکلی رو سرور نیست هم خارج هم سرور دیگرو تست کردم و مشکلی رو سرعت خود سرورها نیست

آپدیت جدید هم تست کردید ؟ هر نیم ساعت اینکارو می‌کنه . لطفا لاگ هم بررسی کنید و interval reset time رو ببینید . چون الان کسی هست که به من گفته بود مشکلی نداره. به هر حال آپدیت جدید تلاش کردم که با forced kill مشکلات اینطوری رو کمتر کنم . پس لطفاً بررسی کنید و اطلاع بدید . و لاگ هم بررسی بشه و در صورت امکان برای من فرستاده بشه .

**Comment by DevxRF** [comment]
> > اینم در ادامه بگم بررسی کردم دیدم تو این بازه افرادی هم که متصل هستند سرعتش فوق العاده میاد پایین و تو پنل که چک میکنیم اصلا نمیتونن از پورت استفاده کنن در صورتی که اصلا مشکلی رو سرور نیست هم خارج هم سرور دیگرو تست کردم و مشکلی رو سرعت خود سرورها نیست
> 
> آپدیت جدید هم تست کردید ؟ هر نیم ساعت اینکارو می‌کنه . لطفا لاگ هم بررسی کنید و interval reset time رو ببینید . چون الان کسی هست که به من گفته بود مشکلی نداره. به هر حال آپدیت جدید تلاش کردم که با forced kill مشکلات اینطوری رو کمتر کنم . پس لطفاً بررسی کنید و اطلاع بدید . و لاگ هم بررسی بشه و در صورت امکان برای من فرستاده بشه .

حتما من تموم اسکریپت هاتون رو چک کردم و از این اسکریپت بازه ی بیشتری استفاده کردم تقریبا از issue اولی که باز کردم فکر میکنم متوجه بشید منتها الان تو این دو ساعت که تایم ریست رو 10 دقیقه تنظیم کردم فعلا مشکلی روی سرور پیش نیومده که معمولا مشکل بعد از 12 ساعت پیش میومد 

من تایم هر دو سرور رو روی یک لوکیشن تنظیم کردم حتی تایم پنل x-ui رو هم ست کردم با سرورها ولی مشکل پایدار بود

بعد از یه بررسی چند ساعته نتیجه رو اعلام میکنم

**Comment by Azumi67** [comment]
یک مورد دیگری هم بگم در مورد ریورس چیزل . اگر شما هم از چند سرور ایران به یک خارج استفاده میکنید ، باید پورت های هر سرور ایرانی که اضافه میشه فرق کنه، تو آپدیت جدید اینطوری شده . اگر هم چند سرور خارج هستید که مشکلی نیست .

**Comment by DevxRF** [comment]
> .



> یک مورد دیگری هم بگم در مورد ریورس چیزل . اگر شما هم از چند سرور ایران به یک خارج استفاده میکنید ، باید پورت های هر سرور ایرانی که اضافه میشه فرق کنه، تو آپدیت جدید اینطوری شده . اگر هم چند سرور خارج هستید که مشکلی نیست .

تک سرور استفاده میکنم مهندس منتها باز تاکید میکنم که این مشکل ناپایداری یا اتصال با پینگ بالا زمان اتصال تعداد بالا رو سرورها زودتر و رو سرورهای با تعداد اتصال پایین دیرتر رخ میده که باز بسته به نوع کانفیگ این زمان متغیره

نسخه جدید با تنظیم 10دقیقه سرور من فعلا پینگش پایین و استیبل تر شده و هنوز مشکل قطعی یا پینگ بالا براش پیش نیومده تو این چند ساعت که فکر میکنم نتیجه دقیق رو چند ساعت دیگه میتونم بگم

ولی تو ناپایداری های قبلی چیزی که بیشتر از همه توجه من رو جلب کرد بالا بودن تعداد آنلاین ها اما محدود بودن سرعتشون چشمگیر بوده که بعد از ریسارت سرویس های تانل مشکل حل شده من با 50 تا آنلاین سرعت دانلود و آپلودی که تو پنل میدیدم زیر 1مگ در حال استفاده بود که سریعا بعد از ریستارت سرویس های تانل از طریق اسکریپت بعد از گذشت کمتر از چند ثانیه با همون تعداد اتصال مقدارها به حتی 10برابر افزایش پیدا میکنه و تعداد یوزری که متصل نمیشند مجدد متصل میشند ، حتی تو این بازه که وضعیت اتصال به این شکل هست یوزر جدیدی بسازید اصلا قابلیت اتصال رو نداره تا ریستارت بعدی

**Comment by DevxRF** [comment]
اینم بگم که تو نسخه جدید مقدار استفاده از منابع به شدت کاهش پیدا کرده و خیلی وضعیت بهتر شده

**Comment by Azumi67** [comment]
بسیار عالی . به زودی برای سرور های ایرانی که دستور کرون براشون کار نمیکنه هم یک bin bash اضافه میکنم . ممنون از فیدبک

**Comment by DevxRF** [comment]
مهندس مجدد بعد از گذشت چند ساعت تا با تایمر ریست 10 دقیقه ای سرور استفاده ی منابعش به شدت رفت بالا از سی پی یو از 30درصد به 80 و رم از 25 درصد به 90 درصد افزایش پیدا کرد و بعد از ریسارت سرویس از طریق اسکریپت مشکل رفع شد (سرور خارج)

خرجی از دستور tail نداشتم 

journalctl  هم خروجی فقط یه مشت متن راجع به منابع و مجازی سازی شده و محدودیت هاش  بود

**Comment by Azumi67** [comment]
به اول دستور cron سعی کنید

` /bin/bash `

رو اضافه کنید

**Comment by DevxRF** [comment]
> /bin/bash

cron: can't lock /var/run/crond.pid, otherpid may be 876: Resource temporarily unavailable

**Comment by Azumi67** [comment]
> > /bin/bash
> 
> cron: can't lock /var/run/crond.pid, otherpid may be 876: Resource temporarily unavailable

خب تلاش کرده که دستور kill رو انجام بده اما پروسس ۸۷۶ stuck شده. بررسی کنید که چرا قفل شده. ps 876
و بعد kill کنید و بعد daemon رو ریلود کنید

sudo service cron restart

**Comment by DevxRF** [comment]
من به دوتا نتیجه رسیدم که مشکلم رو فعلا رفع کرده

یک با تغییر pid توی فایل cron.pid


دو اینکه این مشکل فقط رو سرور خارج که پنل نصب هست پیش میاد و اینگار تداخلی صورت میگیره که این ریسارت انجام نمیشه که با ریسارت دستی این مشکل حل میشه، این تداخل pid بین پورت و پنل هست چون تو سرور ایران مشکلی پیش نمیاد ، سرویس تو سرور خارج ریست نمیشه رم رفته رفته پر میشه و سرعت میاد پایین پینگ میره بالا و کاربرهای جدید که اصلا وصل نمیشن ولی وقتی دستی ریستارت سرویس انجام میشه هیچ مشکلی پیش نمیاد من فعلا خودم هر 3.4 ساعت یکبار برای کاربر بالا ریسارت رو انجام میدم و وضعیتم عالیه

**Comment by Azumi67** [comment]
> من به دوتا نتیجه رسیدم که مشکلم رو فعلا رفع کرده
> 
> یک با تغییر pid توی فایل cron.pid
> 
> دو اینکه این مشکل فقط رو سرور خارج که پنل نصب هست پیش میاد و اینگار تداخلی صورت میگیره که این ریسارت انجام نمیشه که با ریسارت دستی این مشکل حل میشه، این تداخل pid بین پورت و پنل هست چون تو سرور ایران مشکلی پیش نمیاد ، سرویس تو سرور خارج ریست نمیشه رم رفته رفته پر میشه و سرعت میاد پایین پینگ میره بالا و کاربرهای جدید که اصلا وصل نمیشن ولی وقتی دستی ریستارت سرویس انجام میشه هیچ مشکلی پیش نمیاد من فعلا خودم هر 3.4 ساعت یکبار برای کاربر بالا ریسارت رو انجام میدم و وضعیتم عالیه

میتونید دستور drop cache هم اضافه کنید و نتیجش رو بهم بگید ؟ 
sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"

تنها مشکلش اینه که می‌تونه disk usage رو زیاد کنه .اینو تو دستور کرون بذارید و نتیجش رو بهم بگید
