### ISSUE TITLE
maybe you can try gost

### ISSUE THREAD

**Issue by woodlyer** [Azumi67/Reverse_tls#7]
Your project is good.  
and  
gost is a good proxy and tunnel tool.  
https://github.com/go-gost/gost
It's easy to use and support many protol.  
Not only tls, but also kcp, quic, http ...

Maybe someone can try it, when he need it.  

this cmd make reverse tls port mapping. 
the port :8080 on server map to :80 of localhost.
```
# server 
./gost -L  tls://:9000?bind=true

# client
./gost  -L rtcp://:8080/:80  -F tls://server.com:9000

```

**Comment by Azumi67** [comment]
Hello there! I know that there have been numerous projects focused on gost, and because of this, i have chosen not to pursue it to avoid duplication. I am aware of this project, including gost v3. Thank you sincerely for sharing your thoughts with me
