### ISSUE TITLE
تونل از چند سرور ایران روی یک سرور خارج

### ISSUE THREAD

**Issue by mhosseint** [Azumi67/Reverse_tls#8]
سلام وقت بخیر
از آنجایی که ترافیک روی سرور های ایران محدود است آیا این امکان دارد که قابلیت را به اسکریپت اضافه کنید تا از چند سرور ایران به سرور خارج تونل بزنیم تا ترافیک را تقسیم کنیم؟
مثلا برای تعدادی از کاربران ساب دامنه ای که سرور ایران ۱ متصل است بدیم و به تعدادی کاربر دیگر ساب دامنه دیگری که به سرور ایران ۲ وصل هست بدهیم. ولی در هر دو صورت به یک سرور خارج متصل شوند.
ممنون میشم لطفا این مورد را هم در اسکریپت در نظر بفرمایید.

**Comment by Azumi67** [comment]
سلام. بله وقتی سرم خلوت تر شد بهش نگاه میکنم . اما این تانل منابع بالایی مصرف می‌کنه و باید اینم در نظر داشت . فعلا درگیر کارهای دیگری هستم .

**Comment by mhosseint** [comment]
سلام مجدد
بله متوجه هستم که مصرف منابع بالایی دارد ولی اگر این قابلیت روی اسکریپت باشد بسیار کار آمد است.
آیا امکان دارد بتوانید زمان بندی اعلام کنید که این مورد را برسی بفرمایید؟؟
بنده هم مجبورم سرور های خارجم رو تمدید کنم ولی اگر این قابلیت وجود داشته باشه فقط یک سرور خارج خوب میگیریم و ترافیک را در چند سرور ایران تقسیم میکنم.

**Comment by Azumi67** [comment]
سلام. بهتون قولی نمیدم. اما پس از اینکه بایناری رو به رت هول اضافه کردم ، این هم نگاه میکنم

**Comment by mhosseint** [comment]
سلام وقت بخیر
آیا فرصت کردید این مورد را هم برسی بفرمایید؟

**Comment by Azumi67** [comment]
سلام. در حال حاضر روی یک از تانل ها دارم کار میکنم . اینم نگاه میکنم .
