### ISSUE TITLE
مشکل ریستارت نشدن سروریس

### ISSUE THREAD

**Issue by hayousef68** [Azumi67/Reverse_tls#9]
سلام
مهندس من احساس میکنم تونل خودکار  سر اون تایمی که گذاشتم ریستارت نمیشه واسم چون رم و cpu خیلی درگیر میشه ولی دستس ریستارت میکنم تونل رو میاد زیر ۱۰ درصد هر دوتاش
چجوری متوجه بشم ریستارت انجام میشه یا نه
اگه انجام نمیشه با جه دستوری داخل سرور میشه انجام داد

**Comment by Azumi67** [comment]
سلام. شما میتونید دو کار کنید .یکی با دستور tail که بررسی کنید که کرون رو اجرا می‌کنه یا نه و یا روی یک دقیقه بذارید و هر یک دقیقه استاتوس سرویس رو نگاه کنید و ببینید ریست می‌کنه یا نه . یعنی استاتوس بگیرید و ببینید کی ریست کرده . چون دستور خاصی نیست که اجرا نشه .

**Comment by hayousef68** [comment]
مم

> سلام. شما میتونید دو کار کنید .یکی با دستور tail که بررسی کنید که کرون رو اجرا می‌کنه یا نه و یا روی یک دقیقه بذارید و هر یک دقیقه استاتوس سرویس رو نگاه کنید و ببینید ریست می‌کنه یا نه . یعنی استاتوس بگیرید و ببینید کی ریست کرده . چون دستور خاصی نیست که اجرا نشه .

ممنون از پاسختون.من یکم مبتدی هستم میشه دستورات رو کامل بنویسین برام .میخوام چک کنم سروریس چه تایمی ریستارت شده
